// Components
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";

// Next
import Image from "next/image";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Detail Campaign - RPU",
  description: "Generated by create next app",
};

export default function DetailCampaign() {
  return (
    <section
      id="detail-campaign"
      className="relative inset-0 z-0 flex flex-col gap-4 w-full h-full p-6"
    >
      <section
        id="top-navigation-bar"
        className="flex justify-between items-center"
      >
        <Image
          src="/icons/ArrowLeftBlack.svg"
          alt="icon-arrow-left"
          width={24}
          height={24}
        />

        <Image
          src="/icons/Option.svg"
          alt="icon-filter"
          width={24}
          height={24}
        />
      </section>

      <figure id="campaign" className="flex flex-col gap-3">
        <Image
          src="/images/campaign-1.png"
          alt="campaign"
          width={325}
          height={141}
          className="w-full h-full max-h-36 rounded-[20px]"
        />

        <figcaption
          id="campaign-information"
          className="flex flex-col max-w-[80%] gap-1"
        >
          <h6 id="tags" className="font-bold text-sm text-primary">
            Pendidikan
          </h6>

          <h5 id="title" className="font-bold text-base text-black-primary">
            Let’s help the palestinian for better education
          </h5>

          <p className="font-semibold text-sm text-placeholder mt-1">
            <span className="font-bold text-primary">22</span> Hari Lagi
          </p>
        </figcaption>
      </figure>

      <section id="statistics" className="flex items-center w-full h-fit">
        <section id="left-content" className="flex gap-[10px] p-[10px]">
          <section
            id="box-icon"
            className="flex justify-center items-center w-11 h-11 rounded-xl p-2 bg-primary"
          >
            <Image
              src="/icons/SendWhite.svg"
              alt="icon-send"
              width={24}
              height={24}
            />
          </section>

          <section id="information" className="flex flex-col gap-1">
            <h6 className="font-semibold text-[13px] text-placeholder">
              Target Donasi
            </h6>

            <p className="font-bold text-sm text-black-primary">$15.000</p>
          </section>
        </section>

        <section id="right-content" className="flex gap-[10px] p-[10px]">
          <section
            id="box-icon"
            className="flex justify-center items-center w-11 h-11 rounded-xl p-2 bg-primary"
          >
            <Image
              src="/icons/Chart.svg"
              alt="icon-chart"
              width={24}
              height={24}
            />
          </section>

          <section id="information" className="flex flex-col gap-1">
            <h6 className="font-semibold text-sm text-placeholder">
              Dana Terkumpul
            </h6>

            <p className="font-bold text-sm text-black-primary">$7.532</p>
          </section>
        </section>
      </section>

      <section id="fundraiser">
        <p className="font-semibold text-sm text-placeholder">
          By {""}{" "}
          <span className="font-bold text-primary">Care Organization</span>
        </p>
      </section>

      <section
        id="description"
        className="font-semibold text-sm text-black-primary opacity-80"
      >
        The mission of this donation is to cultivate highly trained and capable
        Palestinian graduates with a proficiency in conversational English that
        will lead to their successful participation in the labor force and their
        contribution to the societal development of the Palestinian community.
      </section>

      <Sheet key="bottom">
        <SheetTrigger asChild>
          <Button className="w-full h-full max-h-16 rounded-2xl bg-primary font-bold text-center text-white text-base py-5 mt-5">
            Donate now
          </Button>
        </SheetTrigger>

        <SheetContent side="bottom">
          <SheetHeader>
            <h1 className="font-sans font-bold text-base text-black-primary">
              How much wanna donate?
            </h1>
          </SheetHeader>

          <section
            id="content"
            className="flex flex-col gap-4 items-center w-full"
          >
            <section
              id="list-options"
              className="grid grid-rows-2 grid-cols-12 gap-4 mt-6 w-full"
            >
              <section
                id="card-option"
                className="flex justify-center items-center col-span-6 w-full h-full max-h-16 bg-white rounded-2xl border border-solid border-[rgba(202, 202, 202, 0.20)] font-bold text-base text-primary"
              >
                $50
              </section>

              <section
                id="card-option"
                className="flex justify-center items-center col-span-6 w-full h-full max-h-16 bg-white rounded-2xl border border-solid border-[rgba(202, 202, 202, 0.20)] font-bold text-base text-primary py-5"
              >
                $100
              </section>

              <section
                id="card-option"
                className="flex justify-center items-center col-span-6 w-full h-full max-h-16 bg-white rounded-2xl border border-solid border-[rgba(202, 202, 202, 0.20)] font-bold text-base text-primary py-5"
              >
                $150
              </section>

              <section
                id="card-option"
                className="flex justify-center items-center col-span-6 w-full h-full max-h-16 bg-white rounded-2xl border border-solid border-[rgba(202, 202, 202, 0.20)] font-bold text-base text-primary py-5"
              >
                $200
              </section>
            </section>

            <span className="font-semibold text-sm text-black-primary">Or</span>

            <div className="relative w-full items-center">
              <Input
                id="nominal"
                type="number"
                placeholder="Masukkan Nominal"
                className="pl-14 min-h-16 rounded-xl bg-input text-base text-black-primary font-normal placeholder:text-placeholder"
              />
              <span className="absolute start-0 inset-y-0 flex items-center justify-center p-5 font-bold text-base text-black-primary">
                Rp.
              </span>
            </div>
          </section>

          <SheetFooter>
            <SheetClose asChild>
              <Button
                type="submit"
                className="w-full h-full max-h-16 rounded-2xl bg-primary font-bold text-center text-white text-base py-5 mt-5"
              >
                Continue
              </Button>
            </SheetClose>
          </SheetFooter>
        </SheetContent>
      </Sheet>
    </section>
  );
}
