"use client";

// Next
import Image from "next/image";
import Link from "next/link";
// import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Donation History - RPU",
//   description: "Generated by create next app",
// };

import { usePathname } from "next/navigation";

export default function DonationHistory() {
  const listMenus = [
    {
      title: "Beranda",
      icon: "/icons/Home.svg",
      href: "/",
    },
    {
      title: "Laporan",
      icon: "/icons/Papper.svg",
      href: "/donation/history",
    },
    {
      title: "Kotak Masuk",
      icon: "/icons/Inbox.svg",
      href: "/inbox",
    },
    {
      title: "Profil",
      icon: "/icons/Profile.svg",
      href: "/profile",
    },
  ];
  const pathname = usePathname();

  return (
    <section
      id="donation-history"
      className="relative inset-0 z-0 flex flex-col gap-8 w-full h-full p-6"
    >
      <section
        id="top-navigation-bar"
        className="flex justify-between items-center"
      >
        <h1 className="font-bold text-xl text-black-primary">
          Donation History<span className="font-bold text-primary">.</span>
        </h1>

        <Link href="/settings">
          <Image
            src="/icons/Option.svg"
            alt="icon-filter"
            width={24}
            height={24}
          />
        </Link>
      </section>

      <section id="history-content" className="flex flex-col gap-4 w-full">
        <section
          id="card"
          className="flex items-center gap-4 p-3 rounded-[20px] bg-white shadow-card-campaign"
        >
          <section id="left-content">
            <Image
              src="/images/campaign-1.png"
              alt="campaign"
              width={80}
              height={80}
              className="w-20 h-20 rounded-2xl"
            />
          </section>

          <section id="right-content" className="flex flex-col gap-1">
            <span id="date" className="font-bold text-sm text-primary">
              22 March 2021
            </span>

            <h6 className="font-bold text-sm text-black-primary">
              Let’s help the palestinian for <br /> better education
            </h6>
          </section>
        </section>

        <section
          id="card"
          className="flex items-center gap-4 p-3 rounded-[20px] bg-white shadow-card-campaign"
        >
          <section id="left-content">
            <Image
              src="/images/campaign-2.png"
              alt="campaign"
              width={80}
              height={80}
              className="w-20 h-20 rounded-2xl"
            />
          </section>

          <section id="right-content" className="flex flex-col gap-1">
            <span id="date" className="font-bold text-sm text-primary">
              22 March 2021
            </span>

            <h6 className="font-bold text-sm text-black-primary">
              Let’s make our earth green <br /> and healthy
            </h6>
          </section>
        </section>

        <section
          id="card"
          className="flex items-center gap-4 p-3 rounded-[20px] bg-white shadow-card-campaign"
        >
          <section id="left-content">
            <Image
              src="/images/campaign-3.png"
              alt="campaign"
              width={80}
              height={80}
              className="w-20 h-20 rounded-2xl"
            />
          </section>

          <section id="right-content" className="flex flex-col gap-1">
            <span id="date" className="font-bold text-sm text-primary">
              22 March 2021
            </span>

            <h6 className="font-bold text-sm text-black-primary">
              Food donation for hungry
              <br /> people in africa
            </h6>
          </section>
        </section>
      </section>

      <section
        id="bottom-navigation-bar"
        className="fixed inset-x-0 bottom-0 z-10 flex justify-around items-center px-5 py-6 h-fit  bg-white shadow-card-profile"
      >
        {listMenus.map((menu, index) => (
          <a
            key={`menu-${index}`}
            href={menu.href}
            className="flex flex-col items-center gap-1"
          >
            {menu.href === pathname ? (
              <span
                className={`font-bold text-sm${
                  menu.href === pathname ? " text-primary" : " text-white"
                }`}
              >
                {menu.title}
              </span>
            ) : (
              <Image
                src={menu.icon}
                alt={menu.title}
                width={24}
                height={24}
                className={`${menu.href === pathname && "filter-menu-active"}`}
              />
            )}
          </a>
        ))}
      </section>
    </section>
  );
}
